### PR TITLE
Footer section

### PR DESCRIPTION
**Pull request by Olamarx**
In this PR, I:
    - Added axios because it threw error and I figured axios is used but not part of the dependencies.
    - Added the footer component to all the components.

### CODE REVIEW

**Comment by macterra** [comment]
We should add a single footer component that contains a discord link.

**Comment by Olamarx** [comment]
> We should add a single footer component that contains a discord link.

Oh, I will fix that now.

**Comment by Olamarx** [comment]
@macterra can you please review it again.

Thank you.

**Comment by macterra** [comment]
Looks good, thanks!

**Comment by Olamarx** [comment]
> Looks good, thanks!

Okay @macterra, please if you have any Frontend role you can refer me to, I would appreciate. I am job searching.

Thank you, sir.

**Comment by Olamarx** [comment]
> Looks good, thanks!

Okay @macterra, please if you have any Frontend role you can refer me to, I would appreciate. I am job searching.

By the way, I am following you on LinkedIn and I sent a connection request, I would appreciate if you can accept, sir.

Thank you, sir.

**Pull request merged**
